<?php

define('UPLOAD_DIR', ROOT_DIR . "/uploads/auto_foto/");
define('UPLOAD_URL', $config['http_home_url'] . "uploads/auto_foto/");

$tables = array(
				 'auto_autos'     => array( 'id'             => 'int',
				                            'country_id'     => 'int',
				                            'region_id'      => 'int',
				                            'city_id'        => 'int',
				                            'city_other'     => 'string',
				                            'mark_id'        => 'int',
				                            'model_id'       => 'int',
				                            'model_other'    => 'string',
				                            'capacity_motor' => 'float',
				                            'power'          => 'float',
				                            'race'           => 'int',
				                            'color'          => 'string',
				                            'year'           => 'int',
				                            'cost'           => 'int',
				                            'cost_search'    => 'int',
				                            'currency'       => array('USD', 'EUR', 'RUR'),
				                            'auction'        => 'int',
				                            'xfields'        => 'text',
				                            'exchange'       => 'int',
				                            'description'    => 'string',
				                            'contact_person' => 'string',
				                            'email'          => 'string',
				                            'phone'          => 'string',
				                            'photo'          => 'int',
				                            'photo_count'    => 'int',
				                            'exp_date'       => 'int',
				                            'add_date'       => 'int',
				                            'update_date'    => 'int',
				                            'block_date'     => 'int',
				                            'allow_block'    => 'int',
				                            'allow_site'     => 'int',
				                            'author'         => 'string',
				                            'author_id'      => 'int',
				                            'guest_session'  => 'string',
				                            'view_count'     => 'int',
),
				 'auto_marks'     => array( 'id'       => 'int',
				                            'name'     => 'string',
				                            'alt_name' => 'string',
				                            'auto_num' => 'int',
),
				 'auto_models'    => array( 'id'       => 'int',
				                            'mark_id'  => 'int',
				                            'name'     => 'string',
				                            'alt_name' => 'string',
				                            'auto_num' => 'int',
),
				 'auto_countries' => array( 'id'       => 'int',
				                            'name'     => 'string',
				                            'alt_name' => 'string',
),
				 'auto_regions'   => array( 'id'         => 'int',
				                            'country_id' => 'int',
				                            'name'       => 'string',
				                            'alt_name'   => 'string',
),
				 'auto_cities'    => array( 'id'         => 'int',
				                            'country_id' => 'int',
				                            'region_id'  => 'int',
				                            'name'       => 'string',
				                            'alt_name'   => 'string',
),
				 'auto_images'    => array(	'id' 		 => 'int',
				 							'model_id' 	 => 'int',
				 							'auto_id'  	 => 'int',
				 							'image_name' => 'string',
				 							'add_date'   => 'int',
				 							'user_id'    => 'int',
				 							'guest_session' => 'string'
				 							),
				 'auto_fields'    => array(	'id' 		 => 'int',
				 							'title' 	 => 'string',
				 							'description'=> 'string',
				 							'type'  	 => array('text', 'select', 'textarea', 'checkbox'),
				 							'data'       => 'string',
				 							'regex'      => 'string',
				 							'required'   => 'int',
				 							'active'     => 'int',
				 							'default'    => 'string'
				 							),
				''
				);

				foreach ($other_fields_array as $field)
				$tables['auto_autos'][str_replace("_array", '', $field['file'])] = 'int';

				foreach ($checkboxes_array as $column => $name)
				$tables["auto_autos"][$column] = 'int';
				?>